name = "nwr-station-lookup"
main = "index.js"
compatibility_date = "2024-09-01"

[vars]
GH_USER   = "untitledmanifoldguy"
GH_REPO   = "betternwr"
GH_BRANCH = "main"
GH_FOLDER = "nwr_cache"


[[kv_namespaces]]
binding = "NWR_KV"
id = "03b0a0349ad342e1aaea9bf9c34fbd91"